# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_causalgraphs_wrappers", use_symbols = TRUE, package_name = "causalgraphs")

#' @usage NULL
#' @useDynLib causalgraphs, .registration = TRUE
NULL

# Ugly fix 2: ensure that the environment is set correctly (TODO: need to find a fix for this ASAP)
# did this because `self` was not being set correctly in the R6 class
`_self` <- environment()$`_self`

RDAG <- new.env(parent = emptyenv())

RDAG$new <- function() .Call(wrap__RDAG__new)

RDAG$add_node <- function(node, latent) .Call(wrap__RDAG__add_node, `_self`, node, latent)

RDAG$add_nodes_from <- function(nodes, latent) .Call(wrap__RDAG__add_nodes_from, self, nodes, latent)

RDAG$add_edge <- function(u, v, weight) .Call(wrap__RDAG__add_edge, `_self`, u, v, weight)

RDAG$get_parents <- function(node) .Call(wrap__RDAG__get_parents, self, node)

RDAG$get_children <- function(node) .Call(wrap__RDAG__get_children, self, node)

RDAG$get_ancestors_of <- function(nodes) .Call(wrap__RDAG__get_ancestors_of, self, nodes)

RDAG$nodes <- function() .Call(wrap__RDAG__nodes, self)

RDAG$edges <- function() .Call(wrap__RDAG__edges, self)

RDAG$node_count <- function() .Call(wrap__RDAG__node_count, self)

RDAG$edge_count <- function() .Call(wrap__RDAG__edge_count, self)

RDAG$latents <- function() .Call(wrap__RDAG__latents, self)

#' @export
`$.RDAG` <- function (self, name) { func <- RDAG[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RDAG` <- `$.RDAG`


# nolint end
